#!/bin/sh
set -e

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" != "jekyll" ]; then
    echo "ERROR! You can only deploy from jekyll branch"
    exit 1
fi

CLEAN_REPO=$(git status --porcelain)
if [ -n "$CLEAN_REPO" ]; then
    echo "ERROR! Untracked changes in the repo, commit all changes before deploying"
    exit 2
fi

UNPUSHED_COMMITS=$(git cherry -v)
if [ -n "$UNPUSHED_COMMITS" ]; then
    echo "ERROR! Unpushed commits on jekyll branch. Please push all commits before deploying"
    exit 3
fi

CURRENT_SHA=$(git rev-parse HEAD)

echo ""
echo "=> Setting up clean build directory <="
echo ""
rm -rf _site
git clone -b gh-pages git@github.com:thmsmlr/thmsmlr.github.io.git _site

pushd _site
rm -rf $(git ls-tree --name-only master)
popd

echo ""
echo "=> Building site <="
echo ""
jekyll build
pushd _site
git aa
git commit -m "`date` ($CURRENT_SHA)"

echo ""
echo "=> Deploying site <="
echo ""
git push origin master
popd

echo ""
echo "=> Cleaning up <="
echo ""
rm -rf _site
