#!/bin/sh
set -e

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" != "master" ]; then
    echo "ERROR! You can only deploy from master branch"
    exit 1
fi

CLEAN_REPO=$(git status --porcelain)
if [ -n "$CLEAN_REPO" ]; then
    echo "ERROR! Untracked changes in the repo, commit all changes before deploying"
    exit 2
fi

echo ""
echo "=> Setting up clean build directory <="
echo ""
rm -rf _site
git clone -b gh-pages git@github.com:thmsmlr/thmsmlr.github.io.git _site

pushd _site
rm -rf $(git ls-tree --name-only gh-pages)
popd

echo ""
echo "=> Building site <="
echo ""
jekyll build
pushd _site
git aa
git commit -m "Update: `date`"

echo ""
echo "=> Deploying site <="
echo ""
git push origin gh-pages
popd

echo ""
echo "=> Cleaning up <="
echo ""
rm -rf _site
